### ISSUE TITLE
Join in the game Phasmophobia

### ISSUE THREAD

**Issue by RuyArmando** [peedroca/Potions#1]
Play the game with Lucas, Black and Ruy

**Comment by LuucasAugusto** [comment]
exactly

**Comment by peedroca** [comment]
![image](https://user-images.githubusercontent.com/43295412/95005092-0b891d00-05ca-11eb-9305-a1d27d8018a7.png)

**Comment by RuyArmando** [comment]
- [ ] Play now with us

**Comment by RuyArmando** [comment]
Not answered
